create or replace view DM.BI.ACCOUNT_CAS_V_TEMP(
	QUARTER,
	SF_ACCOUNT_ID,
	CAS_CG,
	CAS_CAMPAIGN,
	TOTAL_COMMITTED_SPEND,
	CAS_CG_THRU_NEXT_QTR,
	CAS_CAMPAIGN_THRU_NEXT_QTR,
	TOTAL_COMMITTED_SPEND_THRU_NEXT_QTR,
	NEXT_QTR_CAS_CG,
	NEXT_QTR_CAS_CAMPAIGN,
	NEXT_QTR_TOTAL_COMMITTED_SPEND,
	ACCOUNT_NAME,
	CSM_SUPPORT_TYPE,
	VP_NAME,
	AE_NAME,
	AE_ID
) as 
 
--BASE QUERY, CAS AT ACCOUNT LEVEL


WITH sales_team AS (
      SELECT DISTINCT
        ACCOUNT_OWNER_ID__C as AE_ID,
        AE_NAME,
        VP_SALES_NAME as VP_NAME
    FROM DM.BI.SECURE_SF_REVOPS_ACCOUNTS
),

CAS AS (
    SELECT
        SF_ACCOUNT_ID,
        DATE_TRUNC('QUARTER', METRIC_DATE)::DATE AS QUARTER,
        SUM(METRIC_VALUE) AS TOTAL_COMMITTED_SPEND
    FROM DATA_LAB.REVOPS.CAS_DAILY_OBT
    WHERE METRIC_NAME = 'cas_margin_usd' 
    GROUP BY
        SF_ACCOUNT_ID,
        DATE_TRUNC('QUARTER', METRIC_DATE)
)

SELECT
    CAS.QUARTER,
    CAS.SF_ACCOUNT_ID,
    CAS.TOTAL_COMMITTED_SPEND,
    A.NAME AS ACCOUNT_NAME,
    A.CSM_SUPPORT_TYPE__C AS CSM_SUPPORT_TYPE,
    H.VP_NAME,
    H.AE_NAME,
    H.AE_ID,
    NULL AS CAS_CG,
	NULL AS CAS_CAMPAIGN,
    NULL AS CAS_CG_THRU_NEXT_QTR,
	NULL AS CAS_CAMPAIGN_THRU_NEXT_QTR,
	NULL AS TOTAL_COMMITTED_SPEND_THRU_NEXT_QTR,
	NULL AS NEXT_QTR_CAS_CG,
	NULL AS NEXT_QTR_CAS_CAMPAIGN,
	NULL AS NEXT_QTR_TOTAL_COMMITTED_SPEND
FROM CAS
LEFT JOIN DM.BI.SECURE_SF_REVOPS_ACCOUNTS A
    ON CAS.SF_ACCOUNT_ID = A.ID
LEFT JOIN sales_team H
    ON A.OWNERID = H.AE_ID
ORDER BY
    1,2;