create or replace view DM.BI.ACCOUNT_CAS_V_NEW_TEMP(
	QUARTER,
	SF_ACCOUNT_ID,
	ACCOUNT_ID,
	CHILD_ID,
	TOTAL_COMMITTED_SPEND,
	ACCOUNT_NAME,
	CSM_SUPPORT_TYPE,
	VP_NAME,
	AE_NAME,
	AE_ID,
	CAS_CG,
	CAS_CAMPAIGN,
	CAS_CG_THRU_NEXT_QTR,
	CAS_CAMPAIGN_THRU_NEXT_QTR,
	TOTAL_COMMITTED_SPEND_THRU_NEXT_QTR,
	NEXT_QTR_CAS_CG,
	NEXT_QTR_CAS_CAMPAIGN,
	NEXT_QTR_TOTAL_COMMITTED_SPEND
) as 

WITH sales_team AS (
    SELECT DISTINCT
        ACCOUNT_OWNER_ID__C AS AE_ID,
        AE_NAME,
        VP_SALES_NAME AS VP_NAME
    FROM DM.BI.SECURE_SF_REVOPS_ACCOUNTS
),

CAS AS (
    SELECT
        C.SF_ACCOUNT_ID,
        UA.USER_ID AS ACCOUNT_ID,
        UA.INTACCT_ID AS CHILD_ID,
        DATE_TRUNC('QUARTER', C.METRIC_DATE)::DATE AS QUARTER,
        SUM(C.METRIC_VALUE) AS TOTAL_COMMITTED_SPEND
    FROM DATA_LAB.REVOPS.CAS_DAILY_OBT C
    LEFT JOIN DM.BI.D_USER_ACCOUNT_V UA
        ON C.ACCOUNT_ID = UA.USER_ID
        AND UA.IS_CURRENT = TRUE
    WHERE C.METRIC_NAME = 'cas_margin_usd' 
    GROUP BY
        C.SF_ACCOUNT_ID,
        UA.USER_ID,
        UA.INTACCT_ID,
        DATE_TRUNC('QUARTER', C.METRIC_DATE)
)

SELECT
    CAS.QUARTER,
    CAS.SF_ACCOUNT_ID,
    CAS.ACCOUNT_ID,
    CAS.CHILD_ID,
    CAS.TOTAL_COMMITTED_SPEND,
    A.NAME AS ACCOUNT_NAME,
    A.CSM_SUPPORT_TYPE__C AS CSM_SUPPORT_TYPE,
    H.VP_NAME,
    H.AE_NAME,
    H.AE_ID,
    NULL AS CAS_CG,
	NULL AS CAS_CAMPAIGN,
    NULL AS CAS_CG_THRU_NEXT_QTR,
	NULL AS CAS_CAMPAIGN_THRU_NEXT_QTR,
	NULL AS TOTAL_COMMITTED_SPEND_THRU_NEXT_QTR,
	NULL AS NEXT_QTR_CAS_CG,
	NULL AS NEXT_QTR_CAS_CAMPAIGN,
	NULL AS NEXT_QTR_TOTAL_COMMITTED_SPEND
FROM CAS
LEFT JOIN DM.BI.SECURE_SF_REVOPS_ACCOUNTS A
    ON CAS.SF_ACCOUNT_ID = A.ID
LEFT JOIN sales_team H
    ON A.OWNERID = H.AE_ID
ORDER BY
    1,2,3,4;