create or replace view E3_FRESHSERVICE_TICKET_TAG_V(
	ID,
	TAG_LIST,
	WORKSPACE,
	STATUS,
	STATUS_NAME,
	PRIORITY,
	PRIORITY_NAME,
	IS_ESCALATED,
	CREATED_AT,
	DUE_BY,
	FR_DUE_BY,
	STATS_RESOLVED_AT,
	STATS_FIRST_RESPONDED_AT,
	RESOLUTION_DAYS,
	QUARTER,
	DESCRIPTION_TEXT,
	CUSTOM_SA_REQUEST_DESCRIPTION_DO_NOT_DELETE,
	CUSTOM_DATE_TEST,
	CUSTOM_EMPLOYEE_HIRE_DATE_EST,
	CUSTOM_INCIDENT_CATEGORY,
	CUSTOM_INCIDENT_SUBCATEGORY,
	CUSTOM_MAJOR_INCIDENT_TYPE,
	CUSTOM_SA_EMPLOYEE_DATE_WAS_REVOKED_EST,
	CUSTOM_SA_HIPO_DO_NOT_DELETE,
	CUSTOM_SA_URGENCY_DO_NOT_DELETE,
	CUSTOM_BUSINESS_IMPACT,
	CUSTOM_IMPACTED_LOCATIONS,
	CUSTOM_NO_OF_CUSTOMERS_IMPACTED,
	CUSTOM_SA_DEPARTMENT,
	CUSTOM_DEV_EFFORTS_HRS,
	CUSTOM_SA_DEPARTMENT_2,
	CUSTOM_SA_REGION,
	CUSTOM_SA_REGION_2,
	CUSTOM_SA_VERTICAL,
	CUSTOM_SA_VERTICAL_2,
	CUSTOM_SA_CUSTOM_EXPORT_FIELD_DO_NOT_USE,
	CUSTOM_STRIPE_INVOICE,
	CUSTOM_FIRSTBASE_ORDER,
	CUSTOM_LF_WHAT_TIER_DOES_THIS_ACCOUNT_FALL_UNDER,
	CUSTOM_LF_SERVICE_DELIVERY_TYPE,
	CUSTOM_INCIDENT_CATEGORY_2,
	CUSTOM_INCIDENT_SUBCATEGORY_2,
	CUSTOM_SA_URGENCY_DO_NOT_DELETE_2,
	CUSTOM_ACCOUNT_SERVICE_TYPE_2,
	CUSTOM_SA_EMPLOYEE_OFFBOARDING_DATE_EST_2,
	CUSTOM_EMPLOYEE_HIRE_DATE_EST_2
) as

SELECT
    t.ID,
    tt.TAG_LIST,
    CASE
        WHEN t.WORKSPACE_ID = 2 THEN 'IT Service Desk'
        WHEN t.WORKSPACE_ID = 4 THEN 'Ad Tech'
        WHEN t.WORKSPACE_ID = 3 THEN 'Engineering'
    END AS workspace,
    t.STATUS,
    CASE t.STATUS
        WHEN 2 THEN 'Open'
        WHEN 3 THEN 'Pending'
        WHEN 4 THEN 'Resolved'
        WHEN 5 THEN 'Closed'
        WHEN 7 THEN 'Custom (7)'
        WHEN 8 THEN 'Custom (8)'
        WHEN 9 THEN 'Custom (9)'
        WHEN 10 THEN 'Custom (10)'
        WHEN 11 THEN 'Custom (11)'
        WHEN 12 THEN 'Custom (12)'
        WHEN 13 THEN 'Custom (13)'
        ELSE 'Unknown (' || t.STATUS || ')'
    END AS status_name,
    t.PRIORITY,
    CASE t.PRIORITY
        WHEN 1 THEN 'Low'
        WHEN 2 THEN 'Medium'
        WHEN 3 THEN 'High'
        WHEN 4 THEN 'Urgent'
        ELSE 'Unknown (' || t.PRIORITY || ')'
    END AS priority_name,
    t.IS_ESCALATED,
    t.CREATED_AT,
    t.DUE_BY,
    t.FR_DUE_BY,
    t.STATS_RESOLVED_AT,
    t.STATS_FIRST_RESPONDED_AT,
    ROUND(DATEDIFF('hour', t.CREATED_AT, t.STATS_RESOLVED_AT) / 24.0, 2) AS resolution_days,
    DATE_TRUNC('quarter', t.CREATED_AT)::DATE AS quarter,
    t.DESCRIPTION_TEXT,
    t.CUSTOM_SA_REQUEST_DESCRIPTION_DO_NOT_DELETE,
    t.CUSTOM_DATE_TEST,
    t.CUSTOM_EMPLOYEE_HIRE_DATE_EST,
    t.CUSTOM_INCIDENT_CATEGORY,
    t.CUSTOM_INCIDENT_SUBCATEGORY,
    t.CUSTOM_MAJOR_INCIDENT_TYPE,
    t.CUSTOM_SA_EMPLOYEE_DATE_WAS_REVOKED_EST,
    t.CUSTOM_SA_HIPO_DO_NOT_DELETE,
    t.CUSTOM_SA_URGENCY_DO_NOT_DELETE,
    t.CUSTOM_BUSINESS_IMPACT,
    t.CUSTOM_IMPACTED_LOCATIONS,
    t.CUSTOM_NO_OF_CUSTOMERS_IMPACTED,
    t.CUSTOM_SA_DEPARTMENT,
    t.CUSTOM_DEV_EFFORTS_HRS,
    t.CUSTOM_SA_DEPARTMENT_2,
    t.CUSTOM_SA_REGION,
    t.CUSTOM_SA_REGION_2,
    t.CUSTOM_SA_VERTICAL,
    t.CUSTOM_SA_VERTICAL_2,
    t.CUSTOM_SA_CUSTOM_EXPORT_FIELD_DO_NOT_USE,
    t.CUSTOM_STRIPE_INVOICE,
    t.CUSTOM_FIRSTBASE_ORDER,
    t.CUSTOM_LF_WHAT_TIER_DOES_THIS_ACCOUNT_FALL_UNDER,
    t.CUSTOM_LF_SERVICE_DELIVERY_TYPE,
    t.CUSTOM_INCIDENT_CATEGORY_2,
    t.CUSTOM_INCIDENT_SUBCATEGORY_2,
    t.CUSTOM_SA_URGENCY_DO_NOT_DELETE_2,
    t.CUSTOM_ACCOUNT_SERVICE_TYPE_2,
    t.CUSTOM_SA_EMPLOYEE_OFFBOARDING_DATE_EST_2,
    t.CUSTOM_EMPLOYEE_HIRE_DATE_EST_2
FROM INB.FRESHSERVICE.TICKET t
LEFT JOIN (
    SELECT TICKET_ID, LISTAGG(TAG_NAME, ', ') WITHIN GROUP (ORDER BY TAG_NAME) AS TAG_LIST
    FROM INB.FRESHSERVICE.TICKET_TAG
    GROUP BY TICKET_ID
) tt
    ON tt.TICKET_ID = t.ID
WHERE t._FIVETRAN_DELETED = FALSE
  AND t.CREATED_AT >= DATE_TRUNC('year', CURRENT_DATE())
  AND t.CREATED_AT < CURRENT_DATE() + 1
  AND t.WORKSPACE_ID IN (2, 3, 4);